### ISSUE TITLE
Errno 8 Exec format error

### ISSUE THREAD

**Issue by rmlb** [CSB5/INC-Seq#5]
**Hi! I get the following error when I try to execute inc-seq.py with the sample input data. I've tried running it on Linux or OSX with the same problem. Do you have any idea what's causing this error?

Thank you!**

users-MacBook-Air-2:INC-Seq-master owner$ ./inc-seq.py -i data/inc_seq_test_read.fa -o consensus.fa
---------- Processing read 1 ----------
Max number of segments found: 20 
Number of segments of the candidate strech: 20
Candidate read found!
Traceback (most recent call last):
  File "./inc-seq.py", line 160, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./inc-seq.py", line 147, in main
    args.seg_cov, args.iterative)
  File "./inc-seq.py", line 24, in callBuildConsensus
    seg_cov, iterative)
  File "/Users/owner/Downloads/INC-Seq-master/utils/buildConsensus.py", line 289, in consensus_blastn
    consensus = pbdagcon(tmpname+'.m5', 0)
  File "/Users/owner/Downloads/INC-Seq-master/utils/buildConsensus.py", line 207, in pbdagcon
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by lch14forever** [comment]
I guess the problem is because PBDAGCON is not executable (by you).

Can you run util/pbdagcon?

What did you get from ls -l util/ ?
