### ISSUE TITLE
No module named 'aligners'

### ISSUE THREAD

**Issue by ghost** [CSB5/INC-Seq#9]
Hi,

I was testing the inc-seq.py script with your data "inc_seq_test_read.fa", however, I keep getting the same error, please see below. I was not able to find online any module named 'aligners'. Would you be able to assist me with this? 

Best regards,
Bilgenur

bb@gtx980 ~/INC-Seq $ python inc-seq.py -i data/inc_seq_test_read.fa -o consensus.fa -a graphmap
Traceback (most recent call last):
  File "inc-seq.py", line 12, in <module>
    from utils import findUnit, buildConsensus
  File "/home/bb/INC-Seq/utils/findUnit.py", line 8, in <module>
    from aligners import *
ModuleNotFoundError: No module named 'aligners'

**Comment by lch14forever** [comment]
Hi,

Do you have the aligners.py file in ~/INC-Seq/utils/ ?

**Comment by ghost** [comment]
Hi,

Since I cloned the full inc-seq repository, it automatically came in the folder. You can also see the screenshot below. 

![utils](https://user-images.githubusercontent.com/49926834/56623998-c440e380-6604-11e9-91ac-ed067a6beb08.png)

**Comment by lch14forever** [comment]
Are you using python3? I think the importing is a bit different in python3 according to [this answer](https://stackoverflow.com/a/45556023/10543838). You may try the fix mentioned using 2to3.

**Comment by IainPerry** [comment]
I recently have encountered the same issue. Tried several versions of python 2 and 3. Not sure if the issue is while 'find unit' and 'build consensus' are given the folder utils "from utils import findUnit, buildConsensus" to look in, 'aligners' is not despite being in utils. I tried changing 'buildConsensus' and 'findUnit' to have the line "from utils import aligners" which gets rid on the error but i am left with:

./inc-seq.py -i data/inc_seq_test_read.fa -o test.fa
---------- Processing read 1 ----------
Traceback (most recent call last):
  File "./inc-seq.py", line 160, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./inc-seq.py", line 137, in main
    args.anchor_cov)
  File "/scratch/user/INC-Seq/utils/findUnit.py", line 31, in find_unit_blastn
    tmpname = tmp_folder + hashlib.md5(record.id).hexdigest() + ".tmp"
TypeError: Unicode-objects must be encoded before hashing

**Comment by lch14forever** [comment]
This seems to be again a python3 compatibility issue: https://stackoverflow.com/questions/7585307/how-to-correct-typeerror-unicode-objects-must-be-encoded-before-hashing

It might be fixed by:
```python
tmpname = tmp_folder + hashlib.md5(record.id.encode('utf-8')).hexdigest() + ".tmp"
```

**Comment by IainPerry** [comment]
Thanks for the quick reply. Odd thing is i have python 2.7.3 running (biopython 1.77 and BLAST 2.7.1.

I made the change to findunit.py and that fixed that issue, passing it to xrange having to be altered to range (again a python 3 issue) and then also a float issue which was resolved with changing seqlen/2 to seqlen//2. 
im finally on to solving a "NameError: name 'blastn' is not defined" error. 
I suspect there might be conflicts going on with versions so i might look into building a singularity container and hope that resolves things.
Thanks

**Comment by lch14forever** [comment]
Hi,

For python3 folks, I almost forgot I had previously attempted to create a branch [here](https://github.com/CSB5/INC-Seq/tree/py3).
